# First of all, use the below command to create docker-config-secret for pushing images to your private registry
# kubectl create secret generic docker-config-secret --from-file=/path/to/.docker/config.json -n argo
# for Windows use kubectl create secret generic docker-config-secret --from-file="$env:USERPROFILE\.docker\config.json" -n argo
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate                   # manifest type
metadata:
  name: build-push-wf-template           # name of the workflow template
spec:
  templates:
    - name: build-and-push               # template name
      inputs:                            # inputs section
        artifacts:                       # use artifacts as inputs
        - name: source                   # artifact name
          path: /tmp/source              # artifact path
      volumes:                           # volumes section
        - name: docker-config-secret     # volume name
          secret:
            secretName: docker-config-secret      # docker secret name
      container:
        readinessProbe:                           # readiness probe set in the container
          exec:
            command: [ sh, -c, "buildctl debug workers" ]       # check if buildkit is ready
        image: moby/buildkit:v0.9.3-rootless                    # used image
        volumeMounts:                                           # volume mounts
          - name: docker-config-secret                          # name of the mounted secret
            mountPath: /.docker                                 # mount path
        workingDir: /tmp/source/17-combining-argo-tools/app     # working directory
        env:                                                    # environment variables
          - name: BUILDKITD_FLAGS                               # buildkitd flags name 
            value: --oci-worker-no-process-sandbox              # buildkitd flags value
          - name: DOCKER_CONFIG                                 # docker config name
            value: /.docker                                     # docker config value
        command:
          - buildctl-daemonless.sh                              # buildctl-daemonless.sh
        args:
          - build
          - --frontend
          - dockerfile.v0
          - --local
          - context=.
          - --local
          - dockerfile=.
          - --output
          - type=image,name={{workflow.parameters.nexus-registry}}/nginx:{{workflow.uid}},push=true,registry.insecure=true
        securityContext:
          privileged: true
