apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate                   # manifest type
metadata:
  name: clone-repo-wf-template           # name of the workflow template
spec:
  templates:
    - name: clone-repo                   # template name
      inputs:
        parameters:
          - name: github-username        # github username parameter
          - name: github-token           # github token parameter
          - name: repo-url               # repository url parameter
      outputs:                           # outputs section
        artifacts:                       # artifact as output
        - name: source                   # artifact name - referring to the folder with path below
          path: /tmp/source              # artifact path - the folder is the artifact. It is containing our repository.
      script:                            # script section
        image: alpine/git                # used image
        command: [sh]                    # used command
        source: |                        # script - clone the repo from url to destination path with credentials
          git clone https://{{inputs.parameters.github-username}}:{{inputs.parameters.github-token}}@github.com/entermix123/ArgoCD-Labs.git /tmp/source