apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: update-manifest-wf-template
spec:
  templates:
    - name: update-manifest
      inputs:
        artifacts:
        - name: source
          path: /tmp/source
      script:
        image: alpine/git
        workingDir: /tmp/source/17-combining-argo-tools/argo-rollouts
        command: [sh]
        env:                                    # read credentials from secret
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: github-credentials
                key: username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-credentials
                key: token
          - name: GitHubTokenName
            valueFrom:
              secretKeyRef:
                name: github-credentials
                key: token_name
        source: |
          # sed -i 's|image:.*|image: {{workflow.parameters.nexus-registry}}/argo-demo/nginx:{{workflow.uid}}|' nginx-rollout.yaml
          sed -i 's|image: host.docker.internal:8085/argo-demo/nginx:.*|image: {{workflow.parameters.nexus-registry}}/argo-demo/nginx:{{workflow.uid}}|' nginx-rollouts.yaml      
          git config user.name "$GIT_USERNAME"
          git config user.email "your-email@example.com"
          git add .
          git commit -m "image.tag has been changed to {{workflow.uid}}"
          
          # Push with credentials from env vars
          git remote set-url origin https://${GitHubTokenName}:${GIT_TOKEN}@github.com/entermix123/ArgoCD-Labs.git
          git push origin {{workflow.parameters.branch}}