apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate                   # manifest type
metadata:
  name: update-manifest-wf-template      # name of the workflow template
spec:
  templates:
    - name: update-manifest              # template name
      inputs:
        parameters:                      # set parameters
          - name: nexus-registry         # nexus registry parameter
          - name: branch                 # branch parameter
        artifacts:
        - name: source                   # artifact name
          path: /tmp/source              # artifact path
      script:
        image: alpine/git                # used image
        workingDir: /tmp/source/17-combining-argo-tools/argo-rollouts           # set manifests dir as working dir
        command: [sh]                    # used command
        env:                             # environment variables section
          - name: GITHUB_USERNAME        # github username from secret
            valueFrom:
              secretKeyRef:
                name: github-credentials # secret name
                key: username            # secret key
          - name: GITHUB_TOKEN           # github token from secret
            valueFrom:
              secretKeyRef:
                name: github-credentials # secret name
                key: token               # secret key
        source: |                        # script - update manifest, commit and push changes
          sed -i 's|image:.*|image: {{inputs.parameters.nexus-registry}}/nginx:{{workflow.uid}}|' nginx-rollouts.yml
          git config user.name "$GITHUB_USERNAME"
          git config user.email "${GITHUB_USERNAME}@users.noreply.github.com"
          git remote set-url origin https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/entermix123/ArgoCD-Labs.git
          git add .
          git commit -m "image.tag has been changed to {{workflow.uid}}"
          git push origin {{inputs.parameters.branch}}