apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-generator-ex2-2
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:                                    # match cluster labels
          argocd.argoproj.io/secret-type: cluster       # secret type label set in the local-secret.yaml for local clusters
          # environment: pre-staging                    # if we want to deploy the application only in the local cluster
  template:
    metadata:
      name: '{{name}}-application'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/entermix123/ArgoCD-Labs
        targetRevision: main
        path: argocd-application/helm-charts/nginx
      destination:
        server: '{{server}}'
        namespace: cluster-generator
      syncPolicy:
        automated: {}                                   # automated sync
        syncOptions:
          - CreateNamespace=true                        # automated namespace creation