apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollouts
spec:
  replicas: 5                       # number of replicas
  strategy:
    canary:                         # canary deployment strategy
      steps:
      - setWeight: 20               # 20% of traffic (1 of 5 pods)
      - pause: {}                   # manual promotion
      - setWeight: 40               # 40% of traffic (2 of 5 pods)
      - pause: {duration: 10s}      # 10s pause before autoatic promotion
      - setWeight: 60               # 60% of traffic (3 of 5 pods)
      - pause: {duration: 20s}      # 20s pause before autoatic promotion
      - setWeight: 80               # 80% of traffic (4 of 5 pods)
      - pause: {duration: 1m}       # 1min pause before autoatic promotion
  selector:
    matchLabels:
      app: nginx-rollouts
  template:
    metadata:
      labels:
        app: nginx-rollouts
    spec:
      containers:
      - name: nginx-rollouts
        image: host.docker.internal:8085/nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1                  # backend service of the rollout
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: nginx-rollouts
