apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: merge-generator-ex1
spec:
  generators:                                                 # generators merge configuration
    - merge:
        mergeKeys:                                            # merge keys
          - server                                            # allows to combine outputs from all generators in one output
        generators:                                           # list of generators
          - clusters:                                         # base generator
              values:                                         # default values
                tag: '1.23'                                   # sepcify image tag parameter in 'values.yaml'
                replicas: '1'                                 # specify replicas parameter in 'values.yaml'
          - clusters:                                         # overwrite generator 1
              selector:                                       # cluster selector
                matchLabels:                                  # cluster match label filter
                  environment: 'staging'                      # select cluster with 'staging' label - external cluster
              values:                                         # overwrite values
                tag: '1.24'                                   # overwrite image tag to 1.24
          - list:                                             # overwrite generator 2
              elements:                                       # list of elements (clusters)
                - server: https://kubernetes.default.svc      # target cluster url - local cluster
                  values.replicas: '3'                        # overwrite replicas to 3
  template:
    metadata:
      name: '{{name}}-application'                              # application name based on the cluster name
    spec:
      project: default
      source:
        repoURL: https://github.com/entermix123/ArgoCD-Labs     # used repository
        targetRevision: main                                    # used branch as versioning
        path: argocd-application/helm-charts/nginx              # application source folder path
        helm:
          parameters:                                           # helm parameters
            - name: "image.tag"                                 # target parameter 1
              value: '{{values.tag}}'                           # replace parameter value with generated value from cluster generator
            - name: "replicaCount"                              # target parameter 2
              value: '{{values.replicas}}'                      # replace parameter value with generated value from list generator
      destination:
        server: '{{server}}'                                    # cluster url
        namespace: '{{metadata.labels.environment}}'            # destination namespace name based on cluster environment labels
      syncPolicy:
        automated: {}                                           # automated sync
        syncOptions:
          - CreateNamespace=true                                # automated namespace creation