apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-cluster-application-terraform                       			  # set name
spec:
  destination:
    namespace: terraform					                # set namespace
    name: external-test                         # set the name of the added cluster
  project: default
  source:
    path: argocd-application/directoryOfmanifests
    repoURL: https://github.com/entermix123/ArgoCD-Labs.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true						# enable CreateNamespace parameter
    # automated: {}                   # disable automated sync