apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-cluster-application                       			  # set name
spec:
  destination:
    namespace: argocd					                # set namespace
    name: https://172.18.0.7:6443                         # set the name of the added cluster as its IP address 
  project: default
  source:
    path: argocd-application/directoryOfmanifests
    repoURL: https://github.com/entermix123/ArgoCD-Labs.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true						# enable CreateNamespace parameter
    # automated: {}                   # disable automated sync