apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-directories-generator-ex1
  namespace: argocd
spec:
  generators:                                                         # list of generators
  - git:                                                              # git generator
      repoURL: https://github.com/entermix123/ArgoCD-Labs             # used repo
      revision: main                                                  # used branch as revision
      directories:
      - path: 09-argocd-applicationSet-1/git-generator/resources/*    # path to resources of the application
  template:                                                           # application template
    metadata:
      name: '{{path.basename}}-application'                           # name of the application - app's dirs
    spec:
      project: default
      source:
        repoURL: https://github.com/entermix123/ArgoCD-Labs           # used repo for app template
        targetRevision: main                                          # used branch as revision
        path: '{{path}}'                                              # used path from the generator
      destination:
        server: https://kubernetes.default.svc                        # url of the cluster - local cluster in this example
        namespace: '{{path.basename}}-ns'                             # destination namespace created path.basename - app's dirs
      syncPolicy:
        automated: {}                                                 # automated sync
        syncOptions:
          - CreateNamespace=true                                      # automated namespace creation
