apiVersion: batch/v1
kind: Job
metadata:
  name: mattermost-post-job-failure
  annotations:
    argocd.argoproj.io/hook: SyncFail
spec:
  template:
    spec:
      containers:
        - name: mattermost-failure
          image: mattermost-notifier:v1
          imagePullPolicy: Never
          command: [ "python3", "mattermost_api.py"]
          env:
          - name: message
            value: "MESSAGE FROM ARGOCD: The last sync is: ❌ Sync Failed"
          - name: url
            value: "host.docker.internal"
          - name: token
            value: "ot3edzrgw7yrzxtoaxpi7hu4dw"
          - name: scheme
            value: "http"
          - name: port
            value: "8065"
          - name: channel_name
            value: "argocd-test-phases"
          - name: team_name
            value: "argocdorg"
      restartPolicy: Never
  backoffLimit: 0
