apiVersion: batch/v1
kind: Job
metadata:
  name: health-check-pre-job
  annotations:                                                # set annotation section
    argocd.argoproj.io/hook: PreSync                          # hook for preSync phase
    argocd.argoproj.io/hook-delete-policy: HookFailed        # added HookFailed policy - after fail deletion
spec:
  template:
    spec:
      containers:
        - name: health-check
          image: curlimages/curl
          command: ["/bin/sh", "-c"]
          args: ["if curl -s -o /dev/null -w '%{http_code}' http://host.docker.internal:9999 | grep -q 200; then echo 'Mattermost is up and Running'; exit 0; else echo 'Mattermost is NOT accessible'; exit 1; fi"]
      restartPolicy: Never
  backoffLimit: 0
