apiVersion: argoproj.io/v1alpha1
kind: EventSource				# event source obejct
metadata:
  name: ci
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  gitlab:                      # event source type
    argo-demo:                 # event name - we can hevae multiple events - only one in this example
      projects:
        - "1"                  # project ID in the GitLba repo - gitlab/my-app/settings/general
      webhook:                           # webhook section
        endpoint: /push                  # endpoint
        port: "12000"                    # port
        url: http://host.docker.internal:32073     # custom url that must be reachable from iside our gitlab server !!!
        # url: http://172.17.0.1:32073 if GitLab is running outside Docker - match the GitLab IP address
        # port 32073 is the default Kind cluster HTTP port 
      events:
        - PushEvents              # when we nmake a push event to gitlab it will be detected
      accessToken:
        key: token                      # References the 'token' key
        name: app-repo-credentials          # References the secret gitlab-credentials
      enableSSLVerification: false          # disable SSL verification
      gitlabBaseURL: http://172.17.0.1      # our local gitlab url found via 
      deleteHookOnFinish: true              # the webhook will be deleted when this event source is deleted
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-events-ingress
  namespace: argo-events
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /push
        pathType: Exact                 # Used to match the path exactly for Docker internal network
        backend:
          service:
            name: ci-eventsource-svc
            port:
              number: 12000

# Use if the ingress is connecting out of Docker network
# apiVersion: networking.k8s.io/v1
# kind: Ingress                                  # ingress
# metadata:
#   name: argo-demo-ingress
#   namespace: argo-events
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: argo.events                         # host name of the ingress 
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: ci-eventsource-svc          # the backend service name created by the event source
#             port:
#               number: 12000