apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app-private-repo-ssh
  namespace: argocd  
spec:
  destination:
    namespace: default                		  # where application will be deployed
    server: https://kubernetes.default.svc 	# default kubernetese cluster: terminal --> argocd cluster list --grpc-web
  project: default				                  # use default project for this lab
  source:
    path: helm-charts/nginx			                                            # the path in the repo to the apllication manifests
    repoURL: git@github.com:entermix123/argocd-labs-private-repo.git    		# path to the argocd private repo with ssh credentials
    targetRevision: main			