apiVersion: v1
kind: Secret
metadata:
  name: https-private-repo-secret
  namespace: argocd
  labels:
     argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/entermix123/argocd-labs-private-repo.git
  username: argocd_private_repo
  password: token
