apiVersion: v1
kind: Secret
metadata:
  name: ssh-private-repo-secret-template
  namespace: argocd
  labels:
     argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: git@github.com:entermix123
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    .........................................
    -----END OPENSSH PRIVATE KEY-----
