apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-secret-store
  namespace: argo-events
spec:
  provider:
    vault:
      server: "http://host.docker.internal:8200"
      path: "secret"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleRef:
            name: "openbao-approle"
            key: "role-id"
          secretRef:
            name: "openbao-approle"
            key: "secret-id"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-secret-store
  namespace: argocd
spec:
  provider:
    vault:
      server: "http://host.docker.internal:8200"
      path: "secret"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleRef:
            name: "openbao-approle"
            key: "role-id"
          secretRef:
            name: "openbao-approle"
            key: "secret-id"