# eso-config/secret-store.yaml
# This SecretStore tells ESO how to connect to GitHub
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: github-secret-store
  namespace: argo-events
spec:
  provider:
    github:
      auth:
        token:
          secretRef:
            name: github-token
            key: token
            namespace: external-secrets-system
      owner: YOUR-GITHUB-USERNAME    # CHANGE THIS
      repo: argo-config               # Your repo name

---
# Create SecretStore in argocd namespace as well
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: github-secret-store
  namespace: argocd
spec:
  provider:
    github:
      auth:
        token:
          secretRef:
            name: github-token
            key: token
            namespace: external-secrets-system
      owner: YOUR-GITHUB-USERNAME    # CHANGE THIS
      repo: argo-config