apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-conditional-parameter-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      Conditional parameters provide a way to choose the output parameters based on expression.

      In this example DAG template has two task which will run conditionally based on `when`.

      Based on this condition one of task may not execute. The template's output parameter will be set to the
      executed taks's output result.
    workflows.argoproj.io/version: '>= 3.1.0'
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: flip-coin                         # this is the entrypoint task
            template: flip-coin                     # this is the template to run
          - name: heads                             # name of the task
            depends: flip-coin                      # this task depends on the entrypoint task
            template: heads                         # this is the template to run if the condition below is met
            when: "{{tasks.flip-coin.outputs.result}} == heads"      # this is the condition configured with 'when'
          - name: tails                             # name of the task
            depends: flip-coin                      # this task depends on the entrypoint task
            template: tails                         # this is the template to run if the condition below is met
            when: "{{tasks.flip-coin.outputs.result}} == tails"      # this is the condition configured with 'when'
      outputs:                        # dag template output
        parameters:
          - name: stepresult          # name of the output parameter
            valueFrom:
              expression: "tasks['flip-coin'].outputs.result == 'heads' ? tasks.heads.outputs.result : tasks.tails.outputs.result"
              # teh result of the expression will be set to the output parameter
    
    - name: flip-coin
      script:
        image: python:alpine3.6
        command: [python]               # python script that will generate heads if generated number is 0 or tails if generated number is 1
        source: |
          import random
          print("heads" if random.randint(0,1) == 0 else "tails")
    
    - name: heads
      script:
        image: python:alpine3.6
        command: [python]               # python script that will print heads if condition result is 0
        source: |
          print("heads")
    
    - name: tails                     
      script:
        image: python:alpine3.6
        command: [python]               # python script that will print tails if condition result is 1
        source: |
          print("tails")
