apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: conditional-artifacts-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/description: |
      Conditional artifacts provide a way to choose the output artifacts based on expression.

      In this example the main template has two steps which will run conditionall using `when` .

      Based on the `when` condition one of step will not execute. The main template's output artifact named "result"
      will be set to the executed step's output.
    workflows.argoproj.io/version: '>= 3.1.0'
spec:
  artifactRepositoryRef:
    configMap: artifact-repository 
    # Defining a specific artifact repository for a workflow. there is no need to specify the name of the artifact repository configmap unless
    # its name is artifact-repositories
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: flip-coin                   # this is the entrypoint step
            template: flip-coin               # this is the template to run
        - - name: heads                       # name of the second step
            template: heads                   # this is the template to run if the condition below is met
            when: "{{steps.flip-coin.outputs.result}} == heads"        # this is the condition configured with 'when'
          - name: tails                       # name of the third step
            template: tails                   # this is the template to run if the condition below is met
            when: "{{steps.flip-coin.outputs.result}} == tails"        # this is the condition configured with 'when'
      outputs:                 # invoker template output
        artifacts:             # invoker output is an artifact
          - name: result       # name of the output artifact
            fromExpression: "steps['flip-coin'].outputs.result == 'heads' ? steps.heads.outputs.artifacts.result : steps.tails.outputs.artifacts.result"
            # the result of the expression will be set to the output artifact

    - name: flip-coin                  # this is the first step
      script:
        image: python:alpine3.6
        command: [ python ]            # python script that will generate heads if generated number is 0 or tails if generated number is 1
        source: |
          import random
          print("heads" if random.randint(0,1) == 0 else "tails")

    - name: heads                      # this is the second step 
      script:
        image: python:alpine3.6
        command: [ python ]            # python script that will save text in file (artifact) if condition result is 0
        source: |
          with open("result.txt", "w") as f:
            f.write("it was heads")
      outputs:                         # step output
        artifacts:                     # step output is an artifact
          - name: result               # name of the output artifact
            path: /result.txt          # path of the output artifact

    - name: tails                      # this is the third step
      script:
        image: python:alpine3.6
        command: [ python ]            # python script that will save text in file (artifact) if condition result is 1
        source: |
          with open("result.txt", "w") as f:
            f.write("it was tails")
      outputs:                         # step output
        artifacts:                     # step output is an artifact
          - name: result               # name of the output artifact
            path: /result.txt          # path of the output artifact
