apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-wf-                    # Name of this Workflow
spec:
  arguments:
  entrypoint: dag-template                  # Defines "dag-template" as the "main" template
  templates:
  - name: dag-template                      # Defining the "dag template" as a Template Invocator, You must use one of "dag" or "steps" as a template invocator
    dag:
      tasks:
        - name: A
          template: container-template
          arguments:
        - name: B
          template: script-template
          dependencies: [A]
        - name: C
          template: resource-template
          dependencies: [A, B]
          arguments:
            parameters:
              - name: random_num_in
                value: "{{tasks.B.outputs.parameters.random_num_out}}"      # we use the random number from the script template as an input parameter
        - name: D
          template: delay-template
          dependencies: [A, B, C]
# - name: steps-template # Defining the "steps template" as a Template Invocator, You must use one of "dag" or "steps" as a template invocator
#   steps:
#   - - name: step1
#       template: container-template
#   - - name: step2a
#       template: script-template
#     - name: step2b
#       template: resource-template
#   - - name: step3
#       template: delay-template


  - name: container-template                            # Defining the "container template" as a Template Definition
    container:
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["echo hello from container template"]
  - name: script-template                              # Defining the "script template" as a Template Definition
    script:
      image: python:alpine3.6
      command: [python]     # we are using python to generate a random number with script as save it in a file that we use in the resource template
      source: |
        import random
        i = random.randint(1, 100)
        with open('/tmp/rand-num.txt', 'w') as f:
            f.write(str(i))
        # print(i)
    outputs:
      parameters:
        - name: random_num_out
        # value: "20"                         # we can set a specific value here
          valueFrom:                          # we can also set the value from a file
            path: /tmp/rand-num.txt           # file path - the file we created with the python script
  - name: resource-template                   # Defining the "resource template" as a Template Definition
    inputs:
      parameters:
        - name: random_num_in                 # we use the random number from the script template as an input parameter
    resource:
      action: create                          # Defining the "create" action
      manifest: |                             # Defining the "manifest" from configmap
        apiVersion: v1
        kind: ConfigMap
        metadata:
          generateName: argo-wf-resource-template-cm-
        data:
          created_by: argo-workflows
          random_number_from_script_template: "{{inputs.parameters.random_num_in}}"
  - name: delay-template                             # Defining the "delay template" as a Template Definition
    suspend:
      duration: "20s"
