apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-demo-application                 # application name
  namespace: argocd                           # application namespace - visualize with ArgoCD           
spec:
  destination:
    namespace: argo-demo                      # destination namespace - deployed in the argo-demo namespace
    server: https://kubernetes.default.svc    # destination server
  project: default                            # project
  source:
    path: argo-rollouts                       # path to the rollout manifest
    repoURL: http://172.17.0.1/root/argo-config.git         # config repostiory address
    targetRevision: main                                    # target revision - can be branch, tag or commit
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:                                   # sync options section
      prune: true                                # prune resources - delete resources that are not in the manifest
      selfHeal: true                             # self heal enabled - recreate deleted resources
      # automated: {}                            # automated sync