apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-secret
  namespace: argo-events
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-secret-store
    kind: SecretStore
  target:
    name: github-webhook-secret
    creationPolicy: Owner
  data:
  - secretKey: webhook-secret
    remoteRef:
      key: github-creds
      property: WEBHOOK_SECRET_GITHUB