apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-wf-       # Name of this Workflow (generated - will be used multiple times in different contexts)
spec:
  entrypoint: dag-template                       # Defines "dag-template" as the "main" template
  templates:
  - name: dag-template 
  # Defining the "dag template" as a Template Invocator, You must use one of "dag" or "steps" as a template invocator
    dag:
      tasks:
        - name: A
          template: container-template    # main task - entrypoint
        - name: B
          template: script-template
          dependencies: [A]               # executed after task A
        - name: C
          template: resource-template
          dependencies: [A]               # also executed after task A - in parallel with task B
        - name: D
          template: delay-template        # executed after task B and C
          dependencies: [B, C]
# - name: steps-template # Defining the "steps template" as a Template Invocator, You must use one of "dag" or "steps" as a template invocator
#   steps:                # on each step we invoke specific template. Each step start after the prevous one is completed
#   - - name: step1
#       template: container-template
#   - - name: step2a      # step2a have double dash (main outer list object in the steps) step2a and step2b run in parallel
#       template: script-template
#     - name: step2b      # step2b have single dash (inner object in the specific step) step2a and step2b run in parallel
#       template: resource-template
#   - - name: step3
#       template: delay-template


  - name: container-template                 # Defining the "container template" as a Template Definition
    container:
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["echo Hello from container template"]
  - name: script-template                    # Defining the "script template" as a Template Definition
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        i = random.randint(1, 100)
        print(i)
  - name: resource-template                 # Defining the "resource template" as a Template Definition
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          generateName: argo-wf-resource-template-cm-
        data:
          created_by: argo-workflows
  - name: delay-template                    # Defining the "delay template" as a Template Definition
    suspend:
      duration: "20s"